[package]
name = "bezier_curve_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.12.0"
imgui = "0.1.0"
imgui-opengl-renderer = "0.5.0"
glfw = "0.31.0"

